version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - "./:/var/www"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    working_dir: /var/www
    tty: true
    ports:
      - "8005:8005"
    volumes:
      - "./:/var/www"
      - "./server.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - app
