version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - "./:/var/www"

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    working_dir: /code
    command: >
        bash -c "php artisan migrate
        && php artisan key:generate"
    tty: true
    ports:
      - "8005:8005"
    volumes:
      - "./:/code"
      - "./server.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - app


