version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    volumes:
      - type: volume
        source: ./
        target: /home/steveavertydeveloper/laravel-docker
        read_only: true
        volume:
          nocopy: true

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    working_dir: /home/steveavertydeveloper/laravel-docker
    tty: true
    ports:
      - "8005:8005"
    volumes:
      - type: volume
        source: ./
        target: /home/steveavertydeveloper/laravel-docker
        read_only: true
        volume:
          nocopy: true
      - "./server.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - app
