version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    working_dir: /home/steveavertydeveloper/laravel-docker
    volumes:
      - "./:/home/steveavertydeveloper/laravel-docker"
    command: composer install

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel_webserver
    restart: unless-stopped
    working_dir: /home/steveavertydeveloper/laravel-docker
    tty: true
    ports:
      - "8005:8005"
    working_dir: /home/steveavertydeveloper/laravel-docker
    volumes:
      - "./:/home/steveavertydeveloper/laravel-docker"
      - "./server.conf:/etc/nginx/conf.d/default.conf:ro"
    links:
      - app
